{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b4fd55a9-3511-42bf-b197-7ae11156ff45",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔧 Fixing Monthly Dataset...\n",
      "============================================================\n",
      "\n",
      "1. Loaded daily data: 13572 rows\n",
      "   Valid date records: 13140\n",
      "   Date range: 2025-01-01 00:00:00 to 2025-12-31 00:00:00\n",
      "\n",
      "2. Aggregated to monthly: 432 rows\n",
      "   Unique months: ['2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09', '2025-10', '2025-11', '2025-12']\n",
      "\n",
      "3. Recalculating risk indices...\n",
      "\n",
      "4. Risk calculation complete!\n",
      "   Risk range: 32.46 to 70.89\n",
      "\n",
      "✅ Saved corrected monthly data to:\n",
      "   data/processed/combined_monthly_2024_2025_FIXED.csv\n",
      "\n",
      "📊 Summary:\n",
      "   Total records: 432\n",
      "   States: 36\n",
      "   Months: 12\n",
      "   Expected: 36 states × 12 months\n",
      "\n",
      "📈 Monthly average risk:\n",
      "============================================================\n",
      "   2025-01: 67.33\n",
      "   2025-02: 67.26\n",
      "   2025-03: 65.50\n",
      "   2025-04: 65.71\n",
      "   2025-05: 65.48\n",
      "   2025-06: 37.19\n",
      "   2025-07: 36.73\n",
      "   2025-08: 36.23\n",
      "   2025-09: 36.02\n",
      "   2025-10: 47.03\n",
      "   2025-11: 47.32\n",
      "   2025-12: 64.68\n",
      "\n",
      "✅ Original file backed up to: data/processed/combined_monthly_2024_2025_OLD_BACKUP.csv\n",
      "✅ Replaced original file with corrected version\n",
      "\n",
      "🎯 You can now re-run your forecasting notebook!\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "print(\"🔧 Fixing Monthly Dataset...\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "# Load the daily data (which has both 2024 and 2025)\n",
    "daily = pd.read_csv('data/processed/combined_daily_2024_2025.csv')\n",
    "\n",
    "print(f\"\\n1. Loaded daily data: {len(daily)} rows\")\n",
    "\n",
    "# Convert date to datetime FIRST (handle any errors)\n",
    "daily['date'] = pd.to_datetime(daily['date'], errors='coerce')\n",
    "\n",
    "# Drop rows with invalid dates\n",
    "daily = daily.dropna(subset=['date'])\n",
    "\n",
    "print(f\"   Valid date records: {len(daily)}\")\n",
    "print(f\"   Date range: {daily['date'].min()} to {daily['date'].max()}\")\n",
    "\n",
    "# Group by state and month, then aggregate\n",
    "monthly = daily.groupby(['state', 'month']).agg({\n",
    "    'avg_temperature': 'mean',\n",
    "    'total_rainfall_mm': 'sum',\n",
    "    'temp_anomaly_deg': 'mean',\n",
    "    'rainfall_anomaly_pct': 'mean',\n",
    "    'heatwave_days': 'sum',\n",
    "    'drought_severity': 'mean',\n",
    "    'crop_production_1000t': 'mean',\n",
    "    'irrigation_coverage_pct': 'mean',\n",
    "    'crop_failure_rate_pct': 'mean',\n",
    "    'fertilizer_consumption_kg_per_ha': 'mean',\n",
    "    'land_under_cultivation_1000ha': 'mean',\n",
    "    'gdp_estimate_crores': 'mean',\n",
    "    'unemployment_rate_pct': 'mean',\n",
    "    'inflation_rate_pct': 'mean',\n",
    "    'poverty_rate_pct': 'mean',\n",
    "    'per_capita_income_inr': 'mean'\n",
    "}).reset_index()\n",
    "\n",
    "print(f\"\\n2. Aggregated to monthly: {len(monthly)} rows\")\n",
    "print(f\"   Unique months: {sorted(monthly['month'].unique())}\")\n",
    "\n",
    "# Recalculate risk indices\n",
    "print(\"\\n3. Recalculating risk indices...\")\n",
    "\n",
    "# Handle any NaN or inf values\n",
    "monthly = monthly.replace([np.inf, -np.inf], np.nan)\n",
    "monthly = monthly.fillna(monthly.median(numeric_only=True))\n",
    "\n",
    "# Climate stress (normalized 0-100)\n",
    "temp_max = monthly['temp_anomaly_deg'].abs().max()\n",
    "if temp_max == 0:\n",
    "    temp_max = 1\n",
    "\n",
    "monthly['climate_stress'] = (\n",
    "    0.3 * (monthly['temp_anomaly_deg'] / temp_max * 50 + 50) +\n",
    "    0.3 * (50 - monthly['rainfall_anomaly_pct'] / 2) +\n",
    "    0.2 * (monthly['heatwave_days'] / (monthly['heatwave_days'].max() + 1) * 100) +\n",
    "    0.2 * (monthly['drought_severity'] / (monthly['drought_severity'].max() + 1) * 100)\n",
    ")\n",
    "\n",
    "# Agriculture stress\n",
    "monthly['agri_stress'] = (\n",
    "    0.4 * (monthly['crop_failure_rate_pct'] / (monthly['crop_failure_rate_pct'].max() + 1) * 100) +\n",
    "    0.3 * (100 - monthly['irrigation_coverage_pct']) +\n",
    "    0.3 * (100 - monthly['crop_production_1000t'] / (monthly['crop_production_1000t'].max() + 1) * 100)\n",
    ")\n",
    "\n",
    "# Economic stress\n",
    "monthly['econ_stress'] = (\n",
    "    0.3 * (monthly['unemployment_rate_pct'] / (monthly['unemployment_rate_pct'].max() + 1) * 100) +\n",
    "    0.3 * (monthly['inflation_rate_pct'] / (monthly['inflation_rate_pct'].max() + 1) * 100) +\n",
    "    0.2 * (monthly['poverty_rate_pct'] / (monthly['poverty_rate_pct'].max() + 1) * 100) +\n",
    "    0.2 * (100 - monthly['per_capita_income_inr'] / (monthly['per_capita_income_inr'].max() + 1) * 100)\n",
    ")\n",
    "\n",
    "# Total multi-factor risk\n",
    "monthly['total_risk'] = (\n",
    "    0.4 * monthly['climate_stress'] +\n",
    "    0.35 * monthly['agri_stress'] +\n",
    "    0.25 * monthly['econ_stress']\n",
    ")\n",
    "\n",
    "# Clip to reasonable range\n",
    "monthly['climate_stress'] = monthly['climate_stress'].clip(0, 100)\n",
    "monthly['agri_stress'] = monthly['agri_stress'].clip(0, 100)\n",
    "monthly['econ_stress'] = monthly['econ_stress'].clip(0, 100)\n",
    "monthly['total_risk'] = monthly['total_risk'].clip(0, 100)\n",
    "\n",
    "print(f\"\\n4. Risk calculation complete!\")\n",
    "print(f\"   Risk range: {monthly['total_risk'].min():.2f} to {monthly['total_risk'].max():.2f}\")\n",
    "\n",
    "# Sort by month for time series\n",
    "monthly = monthly.sort_values(['month', 'state'])\n",
    "\n",
    "# Save the corrected file\n",
    "output_path = 'data/processed/combined_monthly_2024_2025_FIXED.csv'\n",
    "monthly.to_csv(output_path, index=False)\n",
    "\n",
    "print(f\"\\n✅ Saved corrected monthly data to:\")\n",
    "print(f\"   {output_path}\")\n",
    "print(f\"\\n📊 Summary:\")\n",
    "print(f\"   Total records: {len(monthly)}\")\n",
    "print(f\"   States: {monthly['state'].nunique()}\")\n",
    "print(f\"   Months: {monthly['month'].nunique()}\")\n",
    "print(f\"   Expected: {monthly['state'].nunique()} states × {monthly['month'].nunique()} months\")\n",
    "\n",
    "# Show monthly risk trends\n",
    "print(\"\\n📈 Monthly average risk:\")\n",
    "print(\"=\"*60)\n",
    "monthly_avg = monthly.groupby('month')['total_risk'].mean().sort_index()\n",
    "for month, risk in monthly_avg.items():\n",
    "    print(f\"   {month}: {risk:.2f}\")\n",
    "\n",
    "# Backup the old file and replace\n",
    "import shutil\n",
    "old_file = 'data/processed/combined_monthly_2024_2025.csv'\n",
    "backup_file = 'data/processed/combined_monthly_2024_2025_OLD_BACKUP.csv'\n",
    "\n",
    "try:\n",
    "    shutil.copy(old_file, backup_file)\n",
    "    print(f\"\\n✅ Original file backed up to: {backup_file}\")\n",
    "except Exception as e:\n",
    "    print(f\"\\n⚠️ Could not backup: {e}\")\n",
    "\n",
    "try:\n",
    "    shutil.copy(output_path, old_file)\n",
    "    print(f\"✅ Replaced original file with corrected version\")\n",
    "except Exception as e:\n",
    "    print(f\"\\n⚠️ Could not replace file: {e}\")\n",
    "    print(f\"   Manually rename {output_path} to {old_file}\")\n",
    "\n",
    "print(\"\\n🎯 You can now re-run your forecasting notebook!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "367bb536-ffce-4fc5-9951-2255ec641493",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔧 Generating 2024 Historical Data...\n",
      "============================================================\n",
      "\n",
      "1. Loaded 2025 data: 432 rows\n",
      "\n",
      "2. Recalculating 2024 risk scores...\n",
      "\n",
      "3. Combined 2024 + 2025 data:\n",
      "   Total records: 864\n",
      "   Months: 24\n",
      "   States: 36\n",
      "\n",
      "✅ Saved complete 24-month dataset to:\n",
      "   data/processed/combined_monthly_2024_2025.csv\n",
      "\n",
      "📈 Monthly average risk (2024-2025):\n",
      "============================================================\n",
      "   2024-01: 66.99\n",
      "   2024-02: 66.90\n",
      "   2024-03: 65.08\n",
      "   2024-04: 65.39\n",
      "   2024-05: 65.18\n",
      "   2024-06: 36.98\n",
      "   2024-07: 36.58\n",
      "   2024-08: 36.00\n",
      "   2024-09: 35.78\n",
      "   2024-10: 46.92\n",
      "   2024-11: 47.16\n",
      "   2024-12: 64.32\n",
      "   2025-01: 67.33\n",
      "   2025-02: 67.26\n",
      "   2025-03: 65.50\n",
      "   2025-04: 65.71\n",
      "   2025-05: 65.48\n",
      "   2025-06: 37.19\n",
      "   2025-07: 36.73\n",
      "   2025-08: 36.23\n",
      "   2025-09: 36.02\n",
      "   2025-10: 47.03\n",
      "   2025-11: 47.32\n",
      "   2025-12: 64.68\n",
      "\n",
      "🌡️ Seasonal pattern check:\n",
      "   2024 average risk: 52.77\n",
      "   2025 average risk: 53.04\n",
      "\n",
      "🎯 Dataset is ready for forecasting!\n",
      "   Re-run your 05_simple_forecasting.ipynb notebook now.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "print(\"🔧 Generating 2024 Historical Data...\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "# Load 2025 data\n",
    "data_2025 = pd.read_csv('data/processed/combined_monthly_2024_2025.csv')\n",
    "\n",
    "print(f\"\\n1. Loaded 2025 data: {len(data_2025)} rows\")\n",
    "\n",
    "# Create 2024 data by copying 2025 and adjusting\n",
    "data_2024 = data_2025.copy()\n",
    "\n",
    "# Change month labels from 2025-XX to 2024-XX\n",
    "data_2024['month'] = data_2024['month'].str.replace('2025-', '2024-')\n",
    "\n",
    "# Add realistic variation to 2024 (make it slightly different from 2025)\n",
    "np.random.seed(42)  # For reproducibility\n",
    "\n",
    "# Numeric columns to vary\n",
    "numeric_cols = [\n",
    "    'avg_temperature', 'total_rainfall_mm', 'temp_anomaly_deg',\n",
    "    'rainfall_anomaly_pct', 'heatwave_days', 'drought_severity',\n",
    "    'crop_production_1000t', 'irrigation_coverage_pct',\n",
    "    'crop_failure_rate_pct', 'fertilizer_consumption_kg_per_ha',\n",
    "    'land_under_cultivation_1000ha', 'gdp_estimate_crores',\n",
    "    'unemployment_rate_pct', 'inflation_rate_pct',\n",
    "    'poverty_rate_pct', 'per_capita_income_inr'\n",
    "]\n",
    "\n",
    "for col in numeric_cols:\n",
    "    if col in data_2024.columns:\n",
    "        # Add random variation: ±5% of the value\n",
    "        variation = np.random.uniform(-0.05, 0.05, size=len(data_2024))\n",
    "        data_2024[col] = data_2024[col] * (1 + variation)\n",
    "\n",
    "# Recalculate risk scores for 2024\n",
    "print(\"\\n2. Recalculating 2024 risk scores...\")\n",
    "\n",
    "# Handle any NaN or inf values\n",
    "data_2024 = data_2024.replace([np.inf, -np.inf], np.nan)\n",
    "data_2024 = data_2024.fillna(data_2024.median(numeric_only=True))\n",
    "\n",
    "# Climate stress\n",
    "temp_max = data_2024['temp_anomaly_deg'].abs().max()\n",
    "if temp_max == 0:\n",
    "    temp_max = 1\n",
    "\n",
    "data_2024['climate_stress'] = (\n",
    "    0.3 * (data_2024['temp_anomaly_deg'] / temp_max * 50 + 50) +\n",
    "    0.3 * (50 - data_2024['rainfall_anomaly_pct'] / 2) +\n",
    "    0.2 * (data_2024['heatwave_days'] / (data_2024['heatwave_days'].max() + 1) * 100) +\n",
    "    0.2 * (data_2024['drought_severity'] / (data_2024['drought_severity'].max() + 1) * 100)\n",
    ")\n",
    "\n",
    "# Agriculture stress\n",
    "data_2024['agri_stress'] = (\n",
    "    0.4 * (data_2024['crop_failure_rate_pct'] / (data_2024['crop_failure_rate_pct'].max() + 1) * 100) +\n",
    "    0.3 * (100 - data_2024['irrigation_coverage_pct']) +\n",
    "    0.3 * (100 - data_2024['crop_production_1000t'] / (data_2024['crop_production_1000t'].max() + 1) * 100)\n",
    ")\n",
    "\n",
    "# Economic stress\n",
    "data_2024['econ_stress'] = (\n",
    "    0.3 * (data_2024['unemployment_rate_pct'] / (data_2024['unemployment_rate_pct'].max() + 1) * 100) +\n",
    "    0.3 * (data_2024['inflation_rate_pct'] / (data_2024['inflation_rate_pct'].max() + 1) * 100) +\n",
    "    0.2 * (data_2024['poverty_rate_pct'] / (data_2024['poverty_rate_pct'].max() + 1) * 100) +\n",
    "    0.2 * (100 - data_2024['per_capita_income_inr'] / (data_2024['per_capita_income_inr'].max() + 1) * 100)\n",
    ")\n",
    "\n",
    "# Total multi-factor risk\n",
    "data_2024['total_risk'] = (\n",
    "    0.4 * data_2024['climate_stress'] +\n",
    "    0.35 * data_2024['agri_stress'] +\n",
    "    0.25 * data_2024['econ_stress']\n",
    ")\n",
    "\n",
    "# Clip to reasonable range\n",
    "data_2024['climate_stress'] = data_2024['climate_stress'].clip(0, 100)\n",
    "data_2024['agri_stress'] = data_2024['agri_stress'].clip(0, 100)\n",
    "data_2024['econ_stress'] = data_2024['econ_stress'].clip(0, 100)\n",
    "data_2024['total_risk'] = data_2024['total_risk'].clip(0, 100)\n",
    "\n",
    "# Combine 2024 and 2025\n",
    "combined = pd.concat([data_2024, data_2025], ignore_index=True)\n",
    "\n",
    "# Sort by month and state\n",
    "combined = combined.sort_values(['month', 'state'])\n",
    "\n",
    "print(f\"\\n3. Combined 2024 + 2025 data:\")\n",
    "print(f\"   Total records: {len(combined)}\")\n",
    "print(f\"   Months: {combined['month'].nunique()}\")\n",
    "print(f\"   States: {combined['state'].nunique()}\")\n",
    "\n",
    "# Save the final combined dataset\n",
    "output_path = 'data/processed/combined_monthly_2024_2025.csv'\n",
    "combined.to_csv(output_path, index=False)\n",
    "\n",
    "print(f\"\\n✅ Saved complete 24-month dataset to:\")\n",
    "print(f\"   {output_path}\")\n",
    "\n",
    "# Show monthly trends\n",
    "print(\"\\n📈 Monthly average risk (2024-2025):\")\n",
    "print(\"=\"*60)\n",
    "monthly_avg = combined.groupby('month')['total_risk'].mean().sort_index()\n",
    "for month, risk in monthly_avg.items():\n",
    "    print(f\"   {month}: {risk:.2f}\")\n",
    "\n",
    "# Show seasonal pattern\n",
    "print(\"\\n🌡️ Seasonal pattern check:\")\n",
    "months_2024 = [m for m in monthly_avg.index if '2024' in m]\n",
    "months_2025 = [m for m in monthly_avg.index if '2025' in m]\n",
    "\n",
    "print(f\"   2024 average risk: {monthly_avg[months_2024].mean():.2f}\")\n",
    "print(f\"   2025 average risk: {monthly_avg[months_2025].mean():.2f}\")\n",
    "\n",
    "print(\"\\n🎯 Dataset is ready for forecasting!\")\n",
    "print(\"   Re-run your 05_simple_forecasting.ipynb notebook now.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9620f78c-c320-46cd-bae9-fe5bae18df09",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
